//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum;


public class QueryPlainJavaPort extends QueryAbstractPort {

  public QueryPlainJavaPort() {
    super();
  }
  

  public void getNumberOfParts(int parts[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.getNumberOfParts(parts);
      //_destination.unlock();
    //}
  }
  

  public void getQueryDescription(double offset[],double size[],int resolution[],int mids[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.getQueryDescription(offset,size,resolution,mids);
      //_destination.unlock();
    //}
  }
  

  public void forwardAnswer(final double data[],final double distance[],final int indices[],final int rid) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.forwardAnswer(data,distance,indices,rid);
      //_destination.unlock();
    //}
  }
  
  

}
 


