#ifndef DE_TUM_QUERY_H_
#define DE_TUM_QUERY_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include <iostream>
#include <string>



namespace de { 
namespace tum { 
  
     class Query;
} 
}

class de::tum::Query {
  public:
    virtual ~Query(){}
     virtual void forwardAnswer(const double* data, const int data_len,const int rid)=0;
     virtual void getQueryDescription(double* offset, const int offset_len,double* size, const int size_len,int* resolution, const int resolution_len,int* mids, const int mids_len)=0;
     virtual void getNumberOfParts(int& parts)=0;


};

#endif
