//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum;


public class QueryNative2NativePlainPort extends QueryAbstractPort {
  private long _ref;
  public QueryNative2NativePlainPort() {
    super();
    createInstance();
  }
  /**
   * proxy for the native factory method
   */  
  public native void createInstance();
  
  /**
   * frees the memory of the component
   */
  public native void destroyInstance(long ref);
  
  
  /**
   * Connect a uses port.
   *
   * @throw If already connected to another port.
   * @see Operation with name of any implementing component 
   */
  @Override
  public void connect(Query  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super.connect(port);
    connect(_ref,_destination.getReference());
  }
  
  public native void connect(long ref,long cca_application);
   
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  public void disconnect(Query  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
     
     super.disconnect(port);
     destroyInstance(_ref);
  }
  
  
  public long getReference(){
    return _ref;
  }
  
  public void setReference(long ref){
     _ref=ref;
  }

  public void getNumberOfParts(int parts[]) {
    //DO NOTHING HERE
  }
  

  public void getQueryDescription(double offset[],double size[],int resolution[],String mids[]) {
    //DO NOTHING HERE
  }
  

  public void forwardAnswer(final double data[],final double distance[],final int indices[],final int rid) {
    //DO NOTHING HERE
  }
  
  

}
 


