#ifndef DE_TUM_QUERY2NATIVE2JAVAPLAINPORT_H_
#define DE_TUM_QUERY2NATIVE2JAVAPLAINPORT_H_ 

#include "de/tum/Query.h"
#include <jni.h> 
#include <iostream>
//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
#ifdef __cplusplus
  extern "C" {
#endif


          
JNIEXPORT void JNICALL Java_de_tum_QueryNative2JavaPlainPort_createInstance(JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_de_tum_QueryNative2JavaPlainPort_destroyInstance(JNIEnv *env, jobject obj,jlong ref);

#ifdef __cplusplus
  }
#endif




namespace de { 
namespace tum { 
  
     class QueryNative2JavaPlainPort;
} 
}

class de::tum::QueryNative2JavaPlainPort: public de::tum::Query{
  private:
    JavaVM* _jvm;
    jobject _obj;
  public:
    QueryNative2JavaPlainPort(JavaVM* jvm,jobject obj);
    ~QueryNative2JavaPlainPort();
    void getNumberOfParts(int& parts);
    void getQueryDescription(double* offset, const int offset_len,double* size, const int size_len,int* resolution, const int resolution_len,int* mids, const int mids_len);
    void forwardAnswer(const double* data, const int data_len,const int rid);
};
#endif
