//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum;


public class QueryDispatcher implements Query {

  protected java.util.Set<Query>  _destinations;
  
  public QueryDispatcher() {
    _destinations = java.util.Collections.synchronizedSet(new java.util.HashSet<Query>());
  }
  
  public long getReference(){
    return 0;
  }
  
  
  public void setReference(long ref){
  }
  /**
   * Connect a uses port.
   *
   * @throw If already connected to another port.
   * @see Operation with name of any implementing component 
   */
  public void connect(Query  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    if (_destinations==null) {
      throw new de.tum.ascodt.utils.exceptions.ASCoDTException( getClass().getName(), "connect(...)", "port already was connected", null );
    }
    _destinations.add(port);
  }
    
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  public void disconnect(Query  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    if (_destinations==null) {
      throw new de.tum.ascodt.utils.exceptions.ASCoDTException( getClass().getName(), "disconnect(...)", "tried to disconnect port that was not connected before", null );
    }
     
    if (!_destinations.contains(port)) {
      throw new de.tum.ascodt.utils.exceptions.ASCoDTException( getClass().getName(), "disconnect(...)", "tried to disconnect port from port that was not connected before", null );
    }
    _destinations.remove(port);
  }
  
  public boolean isConnected(){
     return !_destinations.isEmpty();
  }
  
  public void getNumberOfParts(int parts[]) {
    for(Query port: _destinations)
      port.getNumberOfParts(parts);
  }
  
  public void getNumberOfPartsForIntegerEnums(int parts[]) {
    for(Query port: _destinations){
      
      port.getNumberOfParts(parts);
      
    }
  }
  public void getQueryDescription(double offset[],double size[],int resolution[],String mids[]) {
    for(Query port: _destinations)
      port.getQueryDescription(offset,size,resolution,mids);
  }
  
  public void getQueryDescriptionForIntegerEnums(double offset[],double size[],int resolution[],String mids[]) {
    for(Query port: _destinations){
      
      port.getQueryDescription(offset,size,resolution,mids);
      
    }
  }
  public void forwardAnswer(final double data[],final double distance[],final int indices[],final int rid) {
    for(Query port: _destinations)
      port.forwardAnswer(data,distance,indices,rid);
  }
  
  public void forwardAnswerForIntegerEnums(final double data[],final double distance[],final int indices[],final int rid) {
    for(Query port: _destinations){
      
      port.forwardAnswer(data,distance,indices,rid);
      
    }
  }
  
//  public void lock() {
//    if (_destination!=null) {
//      _destination.lock();
//    }
//  }
 
//  public void unlock() {
//    if (_destination!=null) {
//      _destination.unlock();
//    }
//  }
  
}
 


