//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum;


public class QueryNative2JavaPlainPort extends QueryAbstractPort {

  private long _ref;
  public QueryNative2JavaPlainPort() {
    super();
    createInstance();
  }
  
  public native void createInstance();
  public native void destroyInstance(long ref);
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  public void disconnect(Query  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
     destroyInstance(_ref);
     super.disconnect(port);
  }
  
  
  public long getReference(){
    return _ref;
  }  
  
  public void setReference(long ref){
     _ref=ref;
  }

  public void getNumberOfParts(int parts[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.getNumberOfParts(parts);
      //_destination.unlock();
    //}
  }
  

  public void getQueryDescription(double offset[],double size[],int resolution[],String mids[]) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.getQueryDescription(offset,size,resolution,mids);
      //_destination.unlock();
    //}
  }
  

  public void forwardAnswer(final double data[],final double distance[],final int indices[],final int rid) {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.forwardAnswer(data,distance,indices,rid);
      //_destination.unlock();
    //}
  }
  


}
 


