//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum;


public class SimNative2JavaPlainPort extends SimAbstractPort {

  private long _ref;
  public SimNative2JavaPlainPort() {
    super();
    createInstance();
  }
  
  public native void createInstance();
  public native void destroyInstance(long ref);
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  public void disconnect(Sim  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
     destroyInstance(_ref);
     super.disconnect(port);
  }
  
  
  public long getReference(){
    return _ref;
  }  
  
  public void setReference(long ref){
     _ref=ref;
  }

  public void sim() {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.sim();
      //_destination.unlock();
    //}
  }
  


}
 


