//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum;


public class SimPlainJavaPort extends SimAbstractPort {

  public SimPlainJavaPort() {
    super();
  }
  

  public void sim() {
   // if (_destination!=null) {
      //_destination.lock();
      _destination.sim();
      //_destination.unlock();
    //}
  }
  
  

}
 


