//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum;


public interface SocketTestA extends de.tum.Query,de.tum.ascodt.repository.entities.CxxReverseRemoteSocketComponent {

  public static final String Implementation = "";
  

}
 


