#ifndef DE_TUM_SOCKETTESTAABSTRACTIMPLEMENTATION_H_
#define DE_TUM_SOCKETTESTAABSTRACTIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include "/work_fast/atanasoa/Programme/runtime-HelloSocketFortran/CxxSocketTests/components/java/de/tum/Query.h"

namespace de { 
namespace tum { 
  
     class SocketTestAAbstractImplementation;
} 
}



class de::tum::SocketTestAAbstractImplementation : public de::tum::Query{
     protected:
          
     public:
       SocketTestAAbstractImplementation();
       virtual ~SocketTestAAbstractImplementation();
};     


#endif
