//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum;


public class SocketTestBBasisJavaImplementation extends de.tum.SocketTestBAbstractJavaImplementation {
  public SocketTestBBasisJavaImplementation( String identifier ) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super(identifier);
  }
  
  /**
   * Provides methods block
   */

}
 

