#ifndef DE_TUM_SOCKETTESTAIMPLEMENTATION_H_
#define DE_TUM_SOCKETTESTAIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
#include "mpi.h"
#include "de/tum/SocketTestAAbstractImplementation.h"
#include <string>
#include <pthread.h>
#include <fstream>
#include <chrono>
#include <vector>

namespace de { 
namespace tum { 

class SocketTestAImplementation;
} 
}

class de::tum::SocketTestAImplementation : public de::tum::SocketTestAAbstractImplementation{
private:
	 const static double global_offset;
	 const static double global_size;
	 const static int global_dimension;
	 pthread_mutex_t _lock;
         std::vector<double> _offset;
	 std::vector<double> _size;
	 std::vector<int> _dimensions;
         std::vector<double> _offset0;
         std::vector<double> _size0;
         std::vector<int> _dimensions0;
	 std::vector<std::string> _mids;
	 double *_data;
	 double *_distances;
	 int *_timesteps;
	 std::chrono::high_resolution_clock::time_point _start;
	 std::ofstream _log_file;
         int _iter;
	 int _rank;
	 int _pieces;
public:
	SocketTestAImplementation();
	~SocketTestAImplementation();
        void gatherMIds();
	void getNumberOfParts(int& parts);
	void getQueryDescription(double* offset, const int offset_len,double* size, const int size_len,int* resolution, const int resolution_len,std::string* mids, const int mids_len);
	void forwardAnswer(
			const double* data,
			const int data_len,
			const double* distance,
			const int distance_len,
			const int* indices,
			const int indices_len,
			const int mid);
    double* getOffset();
	double* getSize();
	void cloneData(double* targetData);
	int* getDimensions();
        void initialiseParallel(int hor, int ver);
	void constructorToString();
};     


#endif
