//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum;


public class SocketTestBJavaImplementation extends SocketTestBBasisJavaImplementation {
  public SocketTestBJavaImplementation( String identifier ) throws de.tum.ascodt.utils.exceptions.ASCoDTException{
    super(identifier);
  }
  
  
  public boolean isValid() {
    // @todo Insert your code here
    return true;
  }


  public boolean hasGUI() {
    // @todo Insert your code here
    return true;
  }
  
  
  public void openGUI() {
	  long startTime = System.currentTimeMillis(); 
	  for(int i=0;i<2;i++)
	  this.sim();
	  System.out.println( "Time:"+(System.currentTimeMillis() - startTime));
  }
  
  
  public void closeGUI() {
    // @todo Insert your code here
  }

  public void destroy(){
     super.destroy();
  }

}
 


