#ifndef DE_TUM_SOCKETTESTAIMPLEMENTATION_H_
#define DE_TUM_SOCKETTESTAIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include "de/tum/SocketTestAAbstractImplementation.h"
#include <string>
#include <pthread.h>
namespace de { 
namespace tum { 

class SocketTestAImplementation;
} 
}

class de::tum::SocketTestAImplementation : public de::tum::SocketTestAAbstractImplementation{
private:
	 pthread_mutex_t _lock;
	 double _offset[2];
	 double _size[2];
	 int _dimensions[2];
	 double *_data;
	 double *_distances;
public:
	SocketTestAImplementation();
	~SocketTestAImplementation();
	void getNumberOfParts(int& parts);
	void getQueryDescription(double* offset, const int offset_len,double* size, const int size_len,int* resolution, const int resolution_len,int* mids, const int mids_len);
	void forwardAnswer(
			const double* data,
			const int data_len,
			const double* distance,
			const int distance_len,
			const int* indices,
			const int indices_len,
			const int mid);
};     


#endif

