CC=gcc
CXX=g++
RM=rm -f
CPPFLAGS= -Icomponents/java -Isrc -I/usr/lib/jvm/java-6-openjdk/include -I/usr/lib/jvm/java-6-openjdk/include/linux -fPIC
LDFLAGS=
LDLIBS=

SRCS= components/java/de/tum/SocketTestBAbstractImplementation.cpp src/de/tum/SocketTestBImplementation.cpp components/java/de/tum/SocketTestBJNIProxy.cpp 
SRCS += components/java/de/tum/QueryNative2JavaPlainPort.cpp components/java/de/tum/QueryNative2NativePlainPort.cpp components/java/de/tum/QueryNativeDispatcher.cpp
OBJS=$(subst .cpp,.o,$(SRCS))

all: libSocketTestB.so

libSocketTestB.so: $(OBJS)
	$(CXX) -shared $(OBJS) -o native/libSocketTestB.so

clean:
	$(RM) $(OBJS)

dist-clean: clean
	$(RM) libSocketTestB.so
