#ifndef DE_TUM_PQIDISPATCHERIMPLEMENTATION_H_
#define DE_TUM_PQIDISPATCHERIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include "de/tum/PQIDispatcherAbstractImplementation.h"
#include <string>
namespace de { 
namespace tum { 
  
     class PQIDispatcherImplementation;
} 
}

class de::tum::PQIDispatcherImplementation : public de::tum::PQIDispatcherAbstractImplementation{
     public:
          PQIDispatcherImplementation();
          ~PQIDispatcherImplementation();
          void requestNumberOfParts(int& parts);
          void requestPartsInformation(double* offset, const int offset_len,double* size, const int size_len,int* dimensions, const int dimensions_len,int* identifiers, const int identifiers_len);
};     


#endif
