//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum;


public class iQueryNative2SocketClientPlainPort extends iQueryAbstractPort {
  private long _ref;
  public iQueryNative2SocketClientPlainPort() {
    super();
    createInstance();
  }
  /**
   * proxy for the native factory method
   */  
  public native void createInstance();
  
  /**
   * frees the memory of the component
   */
  public native void destroyInstance(long ref);
  
  
  /**
   * Connect a uses port.
   *
   * @throw If already connected to another port.
   * @see Operation with name of any implementing component 
   */
  @Override
  public void connect(iQuery  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super.connect(port);
    connect(_ref,_destination.getReference());
  }
  
  public native void connect(long ref,long cca_application);
   
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  public void disconnect(iQuery  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
     
     super.disconnect(port);
     destroyInstance(_ref);
  }
  
  
  public long getReference(){
    return _ref;
  }

  public void requestNumberOfParts(int parts[]) {
    //DO NOTHING HERE
  }
  

  public void requestPartsInformation(double offset[],double size[],int dimensions[],int identifiers[]) {
    //DO NOTHING HERE
  }
  
  

}
 


