//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum;


public class iQueryNative2JavaPlainPort extends iQueryAbstractPort {

  private long _ref;
  public iQueryNative2JavaPlainPort() {
    super();
    createInstance();
  }
  
  public native void createInstance();
  public native void destroyInstance(long ref);
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  public void disconnect(iQuery  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
     destroyInstance(_ref);
     super.disconnect(port);
  }
  
  
  public long getReference(){
    return _ref;
  }  
  

  public void requestNumberOfParts(int parts[]) {
    if (_destination!=null) {
      //_destination.lock();
      _destination.requestNumberOfParts(parts);
      //_destination.unlock();
    }
  }
  

  public void requestPartsInformation(double offset[],double size[],int dimensions[],int identifiers[]) {
    if (_destination!=null) {
      //_destination.lock();
      _destination.requestPartsInformation(offset,size,dimensions,identifiers);
      //_destination.unlock();
    }
  }
  


}
 


