#ifndef DE_TUM_IQUERY2NATIVE2JAVAPLAINPORT_H_
#define DE_TUM_IQUERY2NATIVE2JAVAPLAINPORT_H_ 

#include "de/tum/iQuery.h"
#include <jni.h> 
#include <iostream>
//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
#ifdef __cplusplus
  extern "C" {
#endif


          
JNIEXPORT void JNICALL Java_de_tum_iQueryNative2JavaPlainPort_createInstance(JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_de_tum_iQueryNative2JavaPlainPort_destroyInstance(JNIEnv *env, jobject obj,jlong ref);

#ifdef __cplusplus
  }
#endif




namespace de { 
namespace tum { 
  
     class iQueryNative2JavaPlainPort;
} 
}

class de::tum::iQueryNative2JavaPlainPort: public de::tum::iQuery{
  private:
    JavaVM* _jvm;
    jobject _obj;
  public:
    iQueryNative2JavaPlainPort(JavaVM* jvm,jobject obj);
    ~iQueryNative2JavaPlainPort();
    void requestNumberOfParts(int& parts);
    void requestPartsInformation(double* offset, const int offset_len,double* size, const int size_len,int* dimensions, const int dimensions_len,int* identifiers, const int identifiers_len);
};
#endif
