//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum;


public class iQueryPlainJavaPort extends iQueryAbstractPort {

  public iQueryPlainJavaPort() {
    super();
  }


  public void requestNumberOfParts(int parts[]) {
    if (_destination!=null) {
      //_destination.lock();
      _destination.requestNumberOfParts(parts);
      //_destination.unlock();
    }
  }
  

  public void requestPartsInformation(double offset[],double size[],int dimensions[],int identifiers[]) {
    if (_destination!=null) {
      //_destination.lock();
      _destination.requestPartsInformation(offset,size,dimensions,identifiers);
      //_destination.unlock();
    }
  }
  


}
 


