#ifndef DE_TUM_IQUERY_H_
#define DE_TUM_IQUERY_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include <iostream>
#include <string>



namespace de { 
namespace tum { 
  
     class iQuery;
} 
}

class de::tum::iQuery {
  public:
    virtual ~iQuery(){}
     virtual void requestPartsInformation(double* offset, const int offset_len,double* size, const int size_len,int* dimensions, const int dimensions_len,int* identifiers, const int identifiers_len)=0;
     virtual void requestNumberOfParts(int& parts)=0;


};

#endif
