//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum;


public class iQueryDispatcher implements iQuery {

  protected java.util.HashSet<iQuery>  _destinations;
  
  public iQueryDispatcher() {
    _destinations = new java.util.HashSet<iQuery>();
  }
  
  public long getReference(){
    return 0;
  }

  /**
   * Connect a uses port.
   *
   * @throw If already connected to another port.
   * @see Operation with name of any implementing component 
   */
  public void connect(iQuery  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    if (_destinations==null) {
      throw new de.tum.ascodt.utils.exceptions.ASCoDTException( getClass().getName(), "connect(...)", "port already was connected", null );
    }
    _destinations.add(port);
  }
    
  /**
   * Disconnect a port.
   * 
   * @throw If already not connected to type port.
   * @see Operation with name of any implementing component 
   */
  public void disconnect(iQuery  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    if (_destinations==null) {
      throw new de.tum.ascodt.utils.exceptions.ASCoDTException( getClass().getName(), "disconnect(...)", "tried to disconnect port that was not connected before", null );
    }
     
    if (!_destinations.contains(port)) {
      throw new de.tum.ascodt.utils.exceptions.ASCoDTException( getClass().getName(), "disconnect(...)", "tried to disconnect port from port that was not connected before", null );
    }
    _destinations.remove(port);
  }
  
  public boolean isConnected(){
     return !_destinations.isEmpty();
  }
  
  public void requestNumberOfParts(int parts[]) {
    for(iQuery port: _destinations)
      port.requestNumberOfParts(parts);
  }
  
  public void requestNumberOfPartsForIntegerEnums(int parts[]) {
    for(iQuery port: _destinations){
      
      port.requestNumberOfParts(parts);
      
    }
  }
  public void requestPartsInformation(double offset[],double size[],int dimensions[],int identifiers[]) {
    for(iQuery port: _destinations)
      port.requestPartsInformation(offset,size,dimensions,identifiers);
  }
  
  public void requestPartsInformationForIntegerEnums(double offset[],double size[],int dimensions[],int identifiers[]) {
    for(iQuery port: _destinations){
      
      port.requestPartsInformation(offset,size,dimensions,identifiers);
      
    }
  }
  
//  public void lock() {
//    if (_destination!=null) {
//      _destination.lock();
//    }
//  }
 
//  public void unlock() {
//    if (_destination!=null) {
//      _destination.unlock();
//    }
//  }
  
}
 


