//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum;


public class iQueryNativeDispatcher extends iQueryDispatcher {
  protected long _ref;
  
  public iQueryNativeDispatcher(){
    createInstance();
  }
  
  public native void createInstance(); 
  
  protected void finalize(){
    destroyInstance(_ref);
  }
  
  public native void destroyInstance(long ref);
  
  /**
   * Connect a uses port.
   *
   * @throw If already connected to another port.
   * @see Operation with name of any implementing component 
   */
  public void connect(iQuery  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super.connect(port);
    connect(_ref,port.getReference());
  }
  
  public native void connect(long ref, long portRef);
  
  public void disconnect(iQuery  port) throws de.tum.ascodt.utils.exceptions.ASCoDTException {
    super.disconnect(port);
    disconnect(_ref,port.getReference());
  }
  
  public native void disconnect(long ref, long portRef);

}
