#ifndef DE_TUM_PQIDISPATCHERABSTRACTIMPLEMENTATION_H_
#define DE_TUM_PQIDISPATCHERABSTRACTIMPLEMENTATION_H_ 

//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//

#include "/work/atanasoa/workspace/PQi/PQI-ascodt/components/java/de/tum/iQuery.h"

namespace de { 
namespace tum { 
  
     class PQIDispatcherAbstractImplementation;
} 
}



class de::tum::PQIDispatcherAbstractImplementation : public de::tum::iQuery{
     protected:
          
     public:
       PQIDispatcherAbstractImplementation();
       virtual ~PQIDispatcherAbstractImplementation();
};     


#endif
