//
// ASCoDT - Advanced Scientific Computing Development Toolkit
//
// This file was generated by ASCoDT's simplified SIDL compiler.
//
// Authors: Tobias Weinzierl, Atanas Atanasov   
//
package de.tum;


public interface PQIDispatcher extends de.tum.iQuery,de.tum.ascodt.repository.entities.CxxRemoteSocketComponent {

  public static final String Implementation = "TBD";
  

}
 


